name: Lighthouse Mobile

on:
  push:
    branches: [main]
    paths:
      - "index.html"
      - "styles.css"
      - "assets/**"
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Aguardar deploy Vercel
        run: sleep 75
      - name: Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: https://trucobicarbonato.online/
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./.github/lighthouse-config.json
        continue-on-error: true

